### ISSUE TITLE
Consider using a different namespace

### ISSUE THREAD

**Issue by michalmuskala** [am-kantox/string_naming#1]
It's customary in Elixir for packages not to create modules in namespaces owned by other packages. In this case the `String` namespace is "owned" by the standard library. This guideline is spelt out in [hex docs](https://hex.pm/docs/publish):

> Avoid namespace conflicts with existing packages. Plug owns the Plug namespace, if you have an authentication package for Plug use the namespace PlugAuth instead of Plug.Auth.

The reasoning behind this rule is that the "owning" package can easily define itself a module under the namespace and this would break the library. 

I would suggest `StringNaming` as the main namespace for this package.

**Comment by am-kantox** [comment]
@michalmuskala thanks for pointing this out. I was hesitating between following the same convention as e.g. `String.Casing` and not polluting the core namespace.
