### ISSUE TITLE
Have a sane and minimal config in the code

### ISSUE THREAD

**Issue by derek-zhou** [am-kantox/string_naming#2]
If I add this lib indirectly in the dependencies then it does not compile:
```
==> string_naming
Compiling 1 file (.ex)

== Compilation error in file lib/string_naming.ex ==
** (Protocol.UndefinedError) protocol Enumerable not implemented for nil of type Atom
    (elixir 1.12.3) lib/enum.ex:1: Enumerable.impl_for!/1
    (elixir 1.12.3) lib/enum.ex:141: Enumerable.reduce/3
    (elixir 1.12.3) lib/enum.ex:3958: Enum.filter/2
    lib/string_naming.ex:100: (module)
```
Apparently, it needs a configuration for `config :string_naming, categories`. `config/` for the dependencies is not included for application; so I think it is beneficial to have a sane and minimal default in the code (`lib/` dir) itself as a fallback. It is quite confusing now.

**Comment by am-kantox** [comment]
Indeed. It has been a toy project until today, so I didn’t pay much attention to it. Sec.

**Comment by derek-zhou** [comment]
Please reconsider. How about just a few few character classes of the ASCII as the default. Think about the many applications that may indirectly depend on this lib; it would be unfair to force everyone to write >50 lines of config for a lib that they have not idea and do not know even how it was pulled in.

**Comment by am-kantox** [comment]
Indeed. I will provide the minimal config, required for guards in `md`, hardcoded. Thank you!

**Comment by am-kantox** [comment]
Done in 0e162eec45f41898b3f39291756d3885fc85440c
